### ISSUE TITLE
2.0.0 nuget still in prerelease

### ISSUE THREAD

**Issue by modmoto** [tavis-software/Tavis.Problem#5]
Hi,

we want to upgrade some components to .net standard but the 2.0.0 is still on beta 
 and we do have the policy to not use prereleases in production. As the last checkin was 9 months ago, i thought i would ask here, if this is intended? Or do you need some help testing this? We could use the prerelease on our test systems and see if this works, if you need feedback.

Greetings
Simon

**Comment by darrelmiller** [comment]
I will try and get a new release out later this week.  There have been some other fixes recently merged that I want to get out too.

**Comment by modmoto** [comment]
This is great news, thanks for the immediate feedback. We will be looking forward to the new version :)

**Comment by modmoto** [comment]
Is there any update so far?

**Comment by darrelmiller** [comment]
Sorry no. will do it later today


________________________________

**Comment by darrelmiller** [comment]
Deployed to Nuget.

**Comment by modmoto** [comment]
Thanks a lot, really appreciate it!
